language: cpp

compiler:
#  - gcc
  - clang

os:
  - linux

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install -y autoconf-archive
  - cat /etc/ubuntu-release || true
  - cat /etc/lsb-release || true
  - /bin/ls -l /lib64/libc* || true  
  - /bin/ls -l /lib64/lib* || true  
  - /bin/ls -l /usr/share/aclocal/ax_cxx_*.m4 || true  
  - cat /usr/share/aclocal/ax_cxx_compile_stdcxx_11.m4 || true

before_script:
  - gcc --version
  - clang --version
  - uname -a

script: ./bootstrap && ./configure && make && make check

branches:
  only:
    - configure-travis

notifications:
  email: false
