language: cpp

compiler:
#  - gcc
  - clang

os:
  - linux

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install -y autoconf-archive

before_script:
  - gcc --version
  - clang --version
  - uname -a

script: ./bootstrap && ./configure && make && make check

branches:
  only:
    - configure-travis

notifications:
  email: false
